name: notiflow_flutter
description: Cliente mÃ³vil Flutter para Notiflow (login + mensajes)
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logos/NotiflowV_02.png
    - assets/logos/Naranjo_Degradado.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/Naranjo_Degradado.png"
  adaptive_icon_background: "#FF6B00"
  adaptive_icon_foreground: "assets/logos/Naranjo_Degradado.png"
